# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-24 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studybalancer',
            name='slug',
            field=models.SlugField(default='3dbb590c3618491aa8873fc1daab0529', max_length=255, unique=True),
        ),
    ]
